# Generated by Django 6.0.5 on 2026-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='job_post_limit',
            field=models.IntegerField(default=3),
        ),
    ]
