# Generated by Django 6.0.5 on 2026-06-06 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='company_domain',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='is_verified',
            new_name='verification',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
