# Generated by Django 6.0.5 on 2026-07-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_candidateprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='parsed_resume',
            field=models.TextField(blank=True),
        ),
    ]
