# Generated by Django 6.0.5 on 2026-07-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_atsscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=30),
        ),
    ]
