# Generated by Django 6.0.5 on 2026-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='call_status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
    ]
