# Generated by Django 6.0.5 on 2026-06-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
