# Generated by Django 6.0.5 on 2026-07-28 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_aiinterviewsession_aiquestion_aianswer_calllog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0)),
                ('completeness_score', models.FloatField(default=0)),
                ('keyword_score', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('ai_feedback', models.TextField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='jobs.aianswer')),
            ],
        ),
    ]
