# Generated by Django 6.0.5 on 2026-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
    ]
