# Generated by Django 6.0.5 on 2026-06-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
